/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.filemgmt.views;

/**
 *
 * @author wflores
 */
public class FileItemViewPage extends javax.swing.JPanel {

    /**
     * Creates new form FileItemViewPage
     */
    public FileItemViewPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xImageCanvas1 = new com.rameses.rcp.control.XImageCanvas();

        setLayout(new java.awt.BorderLayout());

        xImageCanvas1.setDepends(new String[] {"fileitem"});
        xImageCanvas1.setName("image"); // NOI18N
        add(xImageCanvas1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XImageCanvas xImageCanvas1;
    // End of variables declaration//GEN-END:variables
}
